### ISSUE TITLE
Migration to GitLab? Addition of PCB designs?

### ISSUE THREAD

**Issue by Sijisu** [Greenscreener/urychlovac#4]
What do you think about that my dear collaborators?

**Comment by Greenscreener** [comment]
Yes, it'll be good, if you migrate to gitlab and add all the interesting sheit. I'm afraid I'm not really able to do so right now.  It'll be lovely if you do.

**Comment by Sijisu** [comment]
Kk, no problema, I'm your man

On July 15, 2019 1:08:48 PM GMT+02:00, Greenscreener <notifications@github.com> wrote:
>Yes, it'll be good, if you migrate to gitlab and add all the
>interesting sheit. I'm afraid I'm not really able to do so right now. 
>It'll be lovely if you do.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Greenscreener/urychlovac/issues/4#issuecomment-511360134

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Sijisu** [comment]
Migration done: :heavy_check_mark: 
Addition of PCB designs: :heavy_multiplication_x:

**Comment by Sijisu** [comment]
Opening that issue there...
